lambda_function_name    = "lambda_authorizer"
s3_bucket_name          = "fonte-codigo-lambda-authorizer"
lambda_s3_key           = "lambda_function.zip"
lambda_role_name        = "lambda_auth_exec_role"
s3_backend_bucket_name  = "tfstate-6soat"
aws_region              = "sa-east-1"
