lambda_function_name   = "lambda_authorizer_clientes"
s3_bucket_name         = "fonte-codigo-lambda-authorizer"
lambda_s3_key          = "lambda_clientes.zip"
lambda_role_name       = "lambda_auth_clientes_exec_role"
s3_backend_bucket_name = "tfstate-6soat"
aws_region             = "sa-east-1"
